### ISSUE TITLE
Can't find plugin on JCenter

### ISSUE THREAD

**Issue by robertsmieja** [Abnaxos/gradle-antlr4-plugin#1]
Were you able to release the plugin on JCenter? I'm receiving an error that Gradle is unable to find the plugin when trying to use it.

I'm currently able to use the plugin through the snapshot release however.

**Comment by Abnaxos** [comment]
Hm. I'll have to learn how that stuff works. I thought, JCenter would sync automatically with Maven Central (at least, other artifacts of mine are available in JCenter without me doing anything about it). But I've also seen that there's some mechanism to do that explicitly via Bintray – which would probably also enable notifications on new releases.

I'll look into this.

**Comment by robertsmieja** [comment]
Closing this issue since it's stale.
